### ISSUE TITLE
[BUG] Game crashes and save file corrupts when breaking Factory Manager that has a disk inside

### ISSUE THREAD

**Issue by Pecco-314** [TeamDman/SuperFactoryManager#169]
Whenever I break the factory manager that has a disk inside (whether the disk is empty or written with codes, and weather in the adventure mode or the creative mode), the game crashes. And when reopening the save, the game crashes again.

I tried breaking the factory manager in a game with only SFM installed, but the crash wasn't reproduced. So I think the bug might be caused by mod conflicts.

**Game Version**: 1.20.1
**Modpack**: All The Mods 9 0.3.2
**SFM Version**: 4.19.0
**Crash Log**:
```
[23:14:42] [Render thread/INFO]: ca.teamdman.sfm.client.gui.screen.ManagerScreen
[23:14:42] [Render thread/ERROR]: ########## GL ERROR ##########
[23:14:42] [Render thread/ERROR]: @ Render
[23:14:42] [Render thread/ERROR]: 65539: Invalid key -1
[23:14:42] [Render thread/ERROR]: ########## GL ERROR ##########
[23:14:42] [Render thread/ERROR]: @ Render
[23:14:42] [Render thread/ERROR]: 65539: Invalid key -1

(many repeated lines)

[23:14:44] [Render thread/ERROR]: ########## GL ERROR ##########
[23:14:44] [Render thread/ERROR]: @ Pre render
[23:14:44] [Render thread/ERROR]: 65539: Invalid key -1
[23:14:44] [Server thread/ERROR]: Exception caught during firing event: Rendersystem called from wrong thread
[23:14:44] [Server thread/ERROR]: Exception caught during firing event: Rendersystem called from wrong thread
	Index: 9
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		2: NORMAL
		3: ASM: mythicbotany.EventListener@369cba52 pickupItem(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		4: ASM: class com.klikli_dev.occultism.handlers.LootEventHandler giveStoneToBlacksmith(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1686/0x00000008013d8d08@53fb9bcc
		6: ASM: class cofh.thermal.core.common.event.TCoreCommonEvents handleEntityItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		7: ASM: me.desht.pneumaticcraft.common.event.UniversalSensorHandler@352e0f2e onItemPickUp(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		8: ASM: class de.mari_023.ae2wtlib.AE2wtlibForge handle(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		9: ASM: stepsword.mahoutsukai.handlers.ServerHandler@76cad530 useItem(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		10: ASM: wayoftime.bloodmagic.util.handler.event.WillHandler@50a244fb onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$1686/0x00000008013d8d08@160f74f1
		12: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		13: ASM: Block{minecraft:air} onPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		14: net.minecraftforge.eventbus.EventBus$$Lambda$1686/0x00000008013d8d08@24af5f68
		15: net.minecraftforge.eventbus.EventBus$$Lambda$1686/0x00000008013d8d08@15615e89
		16: net.minecraftforge.eventbus.EventBus$$Lambda$1686/0x00000008013d8d08@1acb8212
		17: ASM: org.cyclops.cyclopscore.advancement.criterion.ModItemObtainedTrigger@976ac2a onPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		18: ASM: mob_grinding_utils.events.ChickenFuseEvent@4d3e026a startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		19: LOWEST
		20: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler itemPickupEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:184)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:173)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.Window.m_85382_(Window.java:187)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43)
	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokePI(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3710)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants.m_84830_(InputConstants.java:473)
	at TRANSFORMER/sfm@4.19.0/ca.teamdman.sfm.client.ClientStuff.isMoreInfoKeyDown(ClientStuff.java:104)
	at TRANSFORMER/sfm@4.19.0/ca.teamdman.sfm.common.item.DiskItem.m_7626_(DiskItem.java:181)
	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.71/stepsword.mahoutsukai.effects.secret.GeasEffect.hasGeas(GeasEffect.java:149)
	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.71/stepsword.mahoutsukai.effects.secret.GeasEffect.geasItem(GeasEffect.java:52)
	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.71/stepsword.mahoutsukai.handlers.ServerHandler.useItem(ServerHandler.java:403)
	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.71/stepsword.mahoutsukai.handlers.__ServerHandler_useItem_EntityItemPickupEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.7/net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:494)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.item.ItemEntity.m_6123_(ItemEntity.java:349)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_36277_(Player.java:560)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8107_(Player.java:527)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:241)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TeamDman** [comment]
There's a keybind for SFM called "more info key" or something, did you unbind that key? I don't know why that would matter but it looks like mahoutsukai is calling the tooltip fn on the disk item which is checking that key and getting  `65539: Invalid key -1`

**Comment by Pecco-314** [comment]
> There's a keybind for SFM called "more info key" or something, did you unbind that key? I don't know why that would matter but it looks like mahoutsukai is calling the tooltip fn on the disk item which is checking that key and getting `65539: Invalid key -1`

I don't know why but re-binding the key does solve the problem. Thank you.

**Comment by TeamDman** [comment]
I think I adjusted the key bind logic, if this is still happening lmk
