### ISSUE TITLE
Fluid insertion crash

### ISSUE THREAD

**Issue by TeamDman** [TeamDman/SuperFactoryManager#24]
```
Time: 3/29/19 10:08 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at vswe.superfactory.components.CommandExecutor.insertFluids(CommandExecutor.java:688)
        at vswe.superfactory.components.CommandExecutor.executeCommand(CommandExecutor.java:228)
        at vswe.superfactory.components.CommandExecutor.executeChildCommands(CommandExecutor.java:178)
        at vswe.superfactory.components.CommandExecutor.executeCommand(CommandExecutor.java:334)
        at vswe.superfactory.components.CommandExecutor.executeChildCommands(CommandExecutor.java:178)
        at vswe.superfactory.components.CommandExecutor.executeTriggerCommand(CommandExecutor.java:170)
        at vswe.superfactory.tiles.TileEntityManager.activateTrigger(TileEntityManager.java:290)
        at vswe.superfactory.tiles.TileEntityManager.func_73660_a(TileEntityManager.java:259)
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:745)
```
https://github.com/TeamDman/SuperFactoryManager/blob/2.0.X/src/main/java/vswe/superfactory/components/CommandExecutor.java#L688

**Comment by TeamDman** [comment]
https://github.com/TeamDman/SuperFactoryManager/commit/3f48ccdebb58101dc2cbc2103ba1c4eacc987c7a
