### ISSUE TITLE
Mod crashes running on dedicated server

### ISSUE THREAD

**Issue by vRazzzy** [TeamDman/SuperFactoryManager#71]
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.18.1-39.0.63-universal.jar%23113!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:53) ~[forge-1.18.1-39.0.63-universal.jar%23113!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:104) ~[server-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.63.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.1-39.0.63.jar%2323!/:1.0] {}
-- MOD sfm --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.63.jar%23111!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.63.jar%23110!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
		at ca.teamdman.sfm.common.registry.SFMItems.<clinit>(SFMItems.java:30) ~[SuperFactoryManager-1.18.1-4.0.1.jar%2396!/:4.0.1] {re:classloading}
		at ca.teamdman.sfm.SFM.<init>(SFM.java:21) ~[SuperFactoryManager-1.18.1-4.0.1.jar%2396!/:4.0.1] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.63.jar%23111!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.63.jar%23110!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: SuperFactoryManager-1.18.1-4.0.1.jar
	Failure message: Super Factory Manager (sfm) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 4.0.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.1-39.0.63.jar%2323!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at ca.teamdman.sfm.common.registry.SFMItems.<clinit>(SFMItems.java:30) ~[SuperFactoryManager-1.18.1-4.0.1.jar%2396!/:4.0.1] {re:classloading}
	at ca.teamdman.sfm.SFM.<init>(SFM.java:21) ~[SuperFactoryManager-1.18.1-4.0.1.jar%2396!/:4.0.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.63.jar%23111!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.63.jar%23110!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2415152416 bytes (2303 MiB) / 4429185024 bytes (4224 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Microsoft Basic Display Adapter
	Graphics card #0 vendor: (Standard display types) (0x1002)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x68f9
	Graphics card #0 versionInfo: DriverVersion=10.0.17763.1
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 75190.66
	Virtual memory used (MB): 17832.93
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 172.64
	JVM Flags: 1 total; -Xmx10G
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		hexerei-0.1.13.jar                                |Hexerei                       |hexerei                       |0.1.13              |COMMON_SET|Manifest: NOSIGNATURE
		ClearDespawn-forge-1.18.1-1.1.6.jar               |ClearDespawn                  |cleardespawn                  |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		inventorysorter-1.18-19.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |19.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		rhino-forge-1800.1.7-build.94.jar                 |Rhino                         |rhino                         |1800.1.7-build.94   |COMMON_SET|Manifest: NOSIGNATURE
		biggerreactors-1.18.1-0.6.0-beta.0.2.jar          |Bigger Reactors               |biggerreactors                |0.6.0-beta.0.2      |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.18.1-5.0.3.jar                         |Cucumber Library              |cucumber                      |5.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		trashslot-forge-1.18-11.0.1.jar                   |TrashSlot                     |trashslot                     |11.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		jmi-1.18.1-0.7-38.jar                             |JourneyMap Integration        |jmi                           |1.18.1-0.7-38       |COMMON_SET|Manifest: NOSIGNATURE
		flatbedrock-1.4.0-build.6+mc1.18.1.jar            |Flat Bedrock                  |flatbedrock                   |1.4.0-build.6+mc1.18|COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |COMMON_SET|Manifest: NOSIGNATURE
		tesseract-1.0.24-mc1.18.jar                       |Tesseract                     |tesseract                     |1.0.24              |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.3.jar                  |Waystones                     |waystones                     |9.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta11.jar                 |Journeymap                    |journeymap                    |5.8.0beta11         |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.18.1-6.0.5.jar                          |Placebo                       |placebo                       |6.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		phosphophyllite-1.18.1-0.6.0-beta.0.1.jar         |Phosphophyllite               |phosphophyllite               |0.6.0-beta.0.1      |COMMON_SET|Manifest: NOSIGNATURE
		worldborder_1.18.1-2.6.jar                        |World Border                  |worldborder                   |2.6                 |COMMON_SET|Manifest: NOSIGNATURE
		forge-branders-spawnermod-1.18-1.8.14.jar         |Enhanced Mob Spawners         |spawnermod                    |1.8.14              |COMMON_SET|Manifest: NOSIGNATURE
		lootbeams-1.18.1-release-jan1522.jar              |LootBeams                     |lootbeams                     |1.18.1              |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.18.1.4.0.jar                     |Guard Villagers               |guardvillagers                |1.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		Apotheosis-1.18.1-5.2.2.jar                       |Apotheosis                    |apotheosis                    |5.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		Electrodynamics-1.18.1-0.5.9-0.jar                |Electrodynamics               |electrodynamics               |1.18.1-0.5.9-0      |COMMON_SET|Manifest: NOSIGNATURE
		balm-2.4.1+0.jar                                  |Balm                          |balm                          |2.4.1+0             |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.138.jar         |Just Enough Resources         |jeresources                   |0.13.1.138          |COMMON_SET|Manifest: NOSIGNATURE
		ExpOreMod+1.18.x+v1.1.jar                         |Exp Ore Mod                   |exp_ore                       |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		ExtraDisks-1.18.1-2.0.2.jar                       |Extra Disks                   |extradisks                    |1.18.1-2.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.1-39.0.63-universal.jar                |Forge                         |forge                         |39.0.63             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		shetiphiancore-1.18-3.10.2.jar                    |ShetiPhian-Core               |shetiphiancore                |3.10.2              |COMMON_SET|Manifest: NOSIGNATURE
		dcintegration-forge-2.3.5-1.18.jar                |Discord Integration           |dcintegration                 |2.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorage-1.10.0.jar                         |Refined Storage               |refinedstorage                |1.10.0              |COMMON_SET|Manifest: NOSIGNATURE
		indreb-1.18.1-0.12.4.jar                          |Industrial Reborn             |indreb                        |1.18.1-0.12.4       |COMMON_SET|Manifest: NOSIGNATURE
		ConfigurableCane-1.18-2.3.0.jar                   |Configurable Cane             |configurablecane              |2.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAgriculture-1.18.1-5.0.2.jar              |Mystical Agriculture          |mysticalagriculture           |5.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		ZeroCore2-1.18.1-2.1.11.jar                       |Zero CORE 2                   |zerocore                      |1.18.1-2.1.11       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		justenoughkeys-0.5.3-forge.jar                    |Just Enough Keys              |justenoughkeys                |0.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.11              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		theoneprobe-1.18-5.0.3.jar                        |The One Probe                 |theoneprobe                   |1.18-5.0.3          |COMMON_SET|Manifest: NOSIGNATURE
		appliedenergistics2-10.0.1.jar                    |Applied Energistics 2         |ae2                           |10.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.1-1.1.0.73.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.73     |COMMON_SET|Manifest: NOSIGNATURE
		endertanks-1.18-1.11.1.jar                        |EnderTanks                    |endertanks                    |1.11.1              |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |COMMON_SET|Manifest: NOSIGNATURE
		crashutilities-4.0.jar                            |Crash Utilities               |crashutilities                |4.0                 |COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.1-7.1.0-145.jar         |Immersive Engineering         |immersiveengineering          |1.18.1-7.1.0-145    |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.18.1-15.0.0.104-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.104   |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16a-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16a             |COMMON_SET|Manifest: NOSIGNATURE
		wthit-forge-4.4.1.jar                             |wthit                         |wthit                         |4.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		pipez-1.18.1-1.0.1.jar                            |Pipez                         |pipez                         |1.18.1-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.0.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.0      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.1-65.jar                           |Patchouli                     |patchouli                     |1.18.1-65           |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.1.jar                  |Storage Drawers               |storagedrawers                |10.1.1              |COMMON_SET|Manifest: NOSIGNATURE
		Nuclear+Science-1.18.1-0.4.6-0.jar                |Nuclear Science               |nuclearscience                |1.18.1-0.4.6-0      |COMMON_SET|Manifest: NOSIGNATURE
		enderchests-1.18-1.9.0.jar                        |EnderChests                   |enderchests                   |1.9.0               |COMMON_SET|Manifest: NOSIGNATURE
		angelring-1.18-1.5.0.jar                          |Angel Ring                    |angelring                     |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.8.jar                           |WorldEdit                     |worldedit                     |7.2.8+6008-1246d61  |COMMON_SET|Manifest: NOSIGNATURE
		quartz-1.18.1-0.0.0-beta.0.1.jar                  |Quartz                        |quartz                        |0.0.0-beta.0.1      |COMMON_SET|Manifest: NOSIGNATURE
		Assembly+Line-1.18.1-0.4.0-0.jar                  |Assembly Line                 |assemblyline                  |1.18.1-0.4.0-0      |COMMON_SET|Manifest: NOSIGNATURE
		architectury-3.5.11.jar                           |Architectury                  |architectury                  |3.5.11              |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-1801.3.5-build.109.jar          |FTB Library                   |ftblibrary                    |1801.3.5-build.109  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-teams-forge-1801.2.4-build.46.jar             |FTB Teams                     |ftbteams                      |1801.2.4-build.46   |COMMON_SET|Manifest: NOSIGNATURE
		ftb-chunks-forge-1801.3.3-build.113.jar           |FTB Chunks                    |ftbchunks                     |1801.3.3-build.113  |COMMON_SET|Manifest: NOSIGNATURE
		kubejs-forge-1801.4.1-build.271.jar               |KubeJS                        |kubejs                        |1801.4.1-build.271  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-ranks-forge-1801.1.6-build.22.jar             |FTB Ranks                     |ftbranks                      |1801.1.6-build.22   |COMMON_SET|Manifest: NOSIGNATURE
		ftb-essentials-1801.1.6-build.37.jar              |FTB Essentials                |ftbessentials                 |1801.1.6-build.37   |COMMON_SET|Manifest: NOSIGNATURE
		ExtremeReactors2-1.18.1-2.0.38.jar                |Extreme Reactors              |bigreactors                   |1.18.1-2.0.38       |COMMON_SET|Manifest: NOSIGNATURE
		inventoryessentials-forge-1.18-4.0.1.jar          |Inventory Essentials          |inventoryessentials           |4.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		kubejs-immersive-engineering-1801.2.0-build.16.jar|KubeJS Immersive Engineering  |kubejs_immersive_engineering  |1801.2.0-build.16   |COMMON_SET|Manifest: NOSIGNATURE
		ChiselsBits-forge-1.18.1-1.2.77-universal.jar     |Chisels & bits                |chiselsandbits                |1.2.77              |COMMON_SET|Manifest: NOSIGNATURE
		SuperFactoryManager-1.18.1-4.0.1.jar              |Super Factory Manager         |sfm                           |4.0.1               |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 36425dd6-ebcf-4ae6-8f28-6b9b947d24e7
	FML: 39.0
	Forge: net.minecraftforge:39.0.63

**Comment by TeamDman** [comment]
Thanks for the report!
New build should be approved soon
https://www.curseforge.com/minecraft/mc-mods/super-factory-manager/files/3633646

**Comment by TeamDman** [comment]
That file was accidentally marked as 1.16 instead of 1.18 in the curseforge metadata. Should be fixed now
